SELECT * FROM customer;

--- 1. TOTAL REVENUE GENERATED BY MALE AND FEMALE CUSTOMERS

SELECT gender, SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY gender;

--- 2. Customers who used discount but still spent more than average purchase amount

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = "Yes"
AND purchase_amount> (

SELECT
AVG(purchase_amount) AS avg_amount
FROM customer

);

--- 3. Top 5 products with the highest average review rating
 
SELECT item_purchased, ROUND(AVG(review_rating),2) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5 ;

--- 4. Comparing the average purchase amounts between standard and express shipping

SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type= "Express" or shipping_type= "Standard"
GROUP BY shipping_type;

--- 5. Comparing average spend and total revenue between subscribers and non-subscribers

SELECT subscription_status,
ROUND(COUNT(customer_id),2) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--- 6. Products which have the highest percentage of purchases with discount applied 

SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied ="Yes" THEN 1 ELSE 0 END) /COUNT(*) * 100,2) AS discount_rate
FROM customer 
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
  
--- 7. Segmenting customers into new, returning and loyal based on their total number of previous purchases

WITH TEMP1 AS(
SELECT customer_id, previous_purchases,
CASE 
WHEN previous_purchases = 1 THEN "New"
WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
else"Loyal" 
END AS customer_status 
FROM customer
)
SELECT customer_status, COUNT(*) AS num_of_customers
FROM TEMP1
GROUP BY customer_status;

--- 8. Top 3 most purchased products within each category

SELECT category 
FROM customer
GROUP BY category;

WITH item_counts AS (
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER () OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT category, item_rank, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=4;

--- 9. Customers who are repeated buyers( more than 5 previous purchases ) also likely to subscribe

SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--- 10. Revenue contribution of each age group

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
